services:
  wp:
    image: wordpress:6.6.1-php8.1-apache
    ports:
      - 8088:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/canvasflow-auth
      - db_data:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    restart: always
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - ./database:/var/lib/mysql

volumes:
  db_data:
